spring:
  datasource:
    test1:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver
    test2:
      username: root
      password: 123456
      jdbc-url: jdbc:mysql://localhost:3306/test2?serverTimezone=UTC
      driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: localhost
    port: 6379

  kafka:
    topic: topic2
    bootstrap-servers: localhost:9092
    consumer:
      group-id: test-consumer-group


#mybatis:
#  mapper-locations: classpath:mapper/*.xml